#247 - created BasicAuthSlice
artipie/http pull request #248
Opened 2020-10-02 12:54 UTC by olenagerasimova

Closes #247 
I've created `BasicAuthSlice` from `SliceAuth` and `BasicIdentities` and deprecated `Identities`, `SliceAuth` and `BasicIdentities`

2020-10-02 13:27 UTC, olegmoz requested changes
@olenagerasimova thanks, please see two comments

2020-10-02 13:27 UTC, olegmoz commented on src/main/java/com/artipie/http/auth/BasicAuthSlice.java
> +                            new Headers.From(new WwwAuthenticate("Basic"))
@olenagerasimova we have `PREFIX` constant that is also `"Basic"`, but with space. Also `Basic` auth scheme name is used in `Authorization.Basic` class. I'd propose to join them all into single constant.

2020-10-02 13:27 UTC, olegmoz commented on src/test/java/com/artipie/http/auth/BasicAuthSliceTest.java
> +                new Permission.ByName("read", (user, action) -> false)
@olenagerasimova I think we can simplify `new Permission.ByName("read", (user, action) -> false)` to just `(user, action) -> false`

2020-10-02 18:03 UTC, olenagerasimova commented
@olegmoz thanks, corrected. Also, I've added one more test case to make sure headers are parsed correctly.

2020-10-05 08:24 UTC, olegmoz requested changes
@olenagerasimova thanks, still have one concern, please take a look

2020-10-05 08:24 UTC, olegmoz commented on src/main/java/com/artipie/http/auth/BasicAuthSlice.java
> +    public static final String PREFIX = "Basic";
@olenagerasimova name of this field is not really appropriate especially when exposed outside of class. It is a "prefix" when you look at header value as a string, but it's meaning is name authentication scheme which could also be `Bearer`, `Digest` etc. I'd suggest to change this field name to `SCHEME`, that would make more sense to one who reads the code.

2020-10-05 08:30 UTC, olenagerasimova commented
@olegmoz thanks, renamed

2020-10-05 08:32 UTC, olegmoz approved these changes
@olenagerasimova thanks, merging

2020-10-05 10:15 UTC, merged

2020-10-05 10:34 UTC, 0crat commented
Job `gh:artipie/http#248` is not assigned, can't get performer

<!-- https://www.0crat.com/footprint/CT2E6TK9B/e49be61c-2f2b-4cc0-8e1a-17fedb4352dc, version: 0.54.5, hash: ${buildNumber} -->