Multipart implementation
artipie/http pull request #281
Opened 2020-12-20 17:04 UTC by Sammers21

Closes #90

2020-12-20 17:06 UTC, Sammers21 commented
@olegmoz, review the PR please

2020-12-21 08:24 UTC, olegmoz requested changes
@Sammers21 thanks, please see comments

2020-12-21 08:24 UTC, olegmoz commented on src/main/java/com/artipie/http/rq/Multipart.java
> + * @checkstyle StringLiteralsConcatenationCheck (500 lines)
@Sammers21 do not see good reason to use string literals concatenation in this class

2020-12-21 08:24 UTC, olegmoz commented on src/main/java/com/artipie/http/rq/Multipart.java
> +    private final List<ByteBuffer> buffers;
@Sammers21 as I see, the class just stores all buffers and does not really process them in reactive manner. This makes it pointless

2020-12-21 08:24 UTC, olegmoz commented on src/main/java/com/artipie/http/rq/Multipart.java
> +        subscription.request(Long.MAX_VALUE);
@Sammers21 I think that lack of backpressure support should be documented in class description

2020-12-21 08:24 UTC, olegmoz commented on src/main/java/com/artipie/http/rq/Multipart.java
> +        throw new IllegalStateException(throwable);
@Sammers21 I believe the error should be propagated to subscription, jut throwing it here is pointless

2020-12-21 08:24 UTC, olegmoz commented on src/main/java/com/artipie/http/rq/Multipart.java
> +        }
@Sammers21 this method is too big, please split it into multiple methods

2020-12-21 08:24 UTC, olegmoz commented on src/test/java/com/artipie/http/rq/MultipartTest.java
> +                    }).start();
@Sammers21 could you please explain why this code is running in separate `Thread`? Response send should be completed async when `connection.accept` is complete. Right now test looks to be broken. I am not sure that it really checks anything

2020-12-21 10:50 UTC, Sammers21 commented on src/main/java/com/artipie/http/rq/Multipart.java
> +    private final List<ByteBuffer> buffers;
@olegmoz, well, it's not pointless, it makes sense as a first step. The next step is to use ByteSplitter and make it fully reactive.

2020-12-21 10:52 UTC, Sammers21 commented on src/test/java/com/artipie/http/rq/MultipartTest.java
> +                    }).start();
@olegmoz, because `new ByteFlowAsString(Flowable.fromPublisher(mpp).flatMap(part -> part)).value()` will cause a deadlock due to vert.x threading policy

2020-12-21 10:53 UTC, Sammers21 commented on src/main/java/com/artipie/http/rq/Multipart.java
> +        throw new IllegalStateException(throwable);
@olegmoz,  makes sense.

2020-12-21 14:54 UTC, olegmoz commented on src/main/java/com/artipie/http/rq/Multipart.java
> +    private final List<ByteBuffer> buffers;
@Sammers21 it could have been useful if we didn't have non-reactive way to parse multipart. But there is no rush to add some multipart support, we need reactive one. So I'd prefer not to merge non-reactive implementation, as it will give false impression of complete feature

2020-12-21 15:05 UTC, olegmoz commented on src/test/java/com/artipie/http/rq/MultipartTest.java
> +                    }).start();
@Sammers21 does not sound great. Cannot be sure it won't cause deadlock without a thread. The tests needs to be modified so it does not require to spawn a thread for the request

2020-12-27 11:08 UTC, Sammers21 commented on src/test/java/com/artipie/http/rq/MultipartTest.java
> +                    }).start();
@olegmoz, Олег, что значит не уверен? Я тебе говорю 100% что будет деделок. Вместо того чтобы это писать, можно пойти и самому убедиться? Какой ужас

2021-03-18 02:13 UTC, closed without merging

2021-03-18 02:30 UTC, 0crat commented
Job `gh:artipie/http#281` is not assigned, can't get performer

<!-- https://www.0crat.com/footprint/CT2E6TK9B/f2617249-09da-4710-a542-b641683a1fe8, version: 0.55.1, hash: ${buildNumber} -->