#283 - Obtain random free port
artipie/http pull request #284
Opened 2021-01-19 08:57 UTC by genryxy

Closes #283 
Added class for obtaining random free port.

2021-01-19 10:07 UTC, olenagerasimova requested changes
@genryxy please, check my comment

2021-01-19 10:07 UTC, olenagerasimova commented on src/main/java/com/artipie/http/misc/RandomFreePort.java
> +        this.port = RandomFreePort.freePort();
@genryxy hm, I do not think this class should have any fields, it does not make any sence, why we should obtain the port in the ctor. I'd suggest to remove the field and put all logic to the `value()` method and may be rename the `value()` method into `get()` or `obtain()`

2021-01-19 10:16 UTC, genryxy commented on src/main/java/com/artipie/http/misc/RandomFreePort.java
> +        this.port = RandomFreePort.freePort();
@olenagerasimova but in this case method `value()` would be `public static` that is not good. Or it would be better to get rid of field and rework method `value()`?

2021-01-19 11:42 UTC, olenagerasimova commented on src/main/java/com/artipie/http/misc/RandomFreePort.java
> +        this.port = RandomFreePort.freePort();
@genryxy why should it be `static`? I'd suggest to suppress corresponding checkstyle error, do not make the method static, and then usage of this class will look like `int port = new RandomFreePort().get()`

2021-01-19 12:06 UTC, genryxy commented
@olenagerasimova thanks, corrected

2021-01-20 15:07 UTC, genryxy commented
@olegmoz could you please merge this PR

2021-01-20 16:51 UTC, merged

2021-01-20 17:10 UTC, 0crat commented
Job `gh:artipie/http#284` is not assigned, can't get performer

<!-- https://www.0crat.com/footprint/CT2E6TK9B/4eb90d4f-958a-42d4-8d8d-b877362f3636, version: 0.55, hash: ${buildNumber} -->