#212: Add Content-Disposition header for a download slice
artipie/http pull request #287
Opened 2021-02-04 20:11 UTC by andreoss

Per #212:
- Introduce `ContentDispostition` & `ContentFileName`
- Add this header during download

2021-02-08 13:40 UTC, genryxy requested changes
@andreoss thanks, please see comments

2021-02-08 13:40 UTC, genryxy commented on src/main/java/com/artipie/http/headers/ContentDisposition.java
> +}
@andreoss I think it would be better to introduce local variable and initialize this one in ctor instead of calling this method every time

2021-02-08 13:40 UTC, genryxy commented on src/main/java/com/artipie/http/slice/SliceDownload.java
> +                                exist -> {
@andreoss `@checkstyle` is not necessary after introducing variable with result of completion

2021-02-08 13:40 UTC, genryxy commented on src/main/java/com/artipie/http/slice/SliceDownload.java
> +                                            );
@andreoss you can use `RsFull` here because response includes body, header and status

2021-02-08 14:17 UTC, andreoss commented on src/main/java/com/artipie/http/headers/ContentDisposition.java
> +}
@genryxy Done. Though it doesn't seem that so much code in a ctor would be desirable.

2021-02-08 14:17 UTC, andreoss commented on src/main/java/com/artipie/http/slice/SliceDownload.java
> +                                exist -> {
@genryxy Done

2021-02-08 14:17 UTC, andreoss commented on src/main/java/com/artipie/http/slice/SliceDownload.java
> +                                            );
@genryxy Done

2021-02-08 14:21 UTC, genryxy commented on src/main/java/com/artipie/http/headers/ContentDisposition.java
> +}
@andreoss it was better to leave the private method, so not to insert this code into the constructor

2021-02-08 14:48 UTC, andreoss commented on src/main/java/com/artipie/http/headers/ContentDisposition.java
> +}
@genryxy I don't quite get it. Why do you need the method than?

2021-02-08 14:50 UTC, genryxy commented on src/main/java/com/artipie/http/headers/ContentDisposition.java
> +}
@andreoss it'll make constructor clearer

2021-02-08 16:16 UTC, andreoss commented on src/main/java/com/artipie/http/headers/ContentDisposition.java
> +}
@genryxy Done

2021-02-08 17:45 UTC, genryxy approved these changes
@andreoss thanks, looks good
@g4s8 please check/merge

2021-02-09 08:32 UTC, g4s8 requested changes
@andreoss please check my comments

2021-02-09 08:32 UTC, g4s8 commented on src/main/java/com/artipie/http/slice/SliceDownload.java
> +                                                    content
@andreoss `new Headers.From(new ContentFileName(...))` could be used here for self-descriptive composition and to avoid specifying generic types.

2021-02-09 08:32 UTC, g4s8 commented on src/main/java/com/artipie/http/slice/SliceDownload.java
> +                                            )
@andreoss you can use `new RsWithBody(StandardRs.NOT_FOUND, "key not found ...", UTF_8)` here

2021-02-09 09:25 UTC, andreoss commented on src/main/java/com/artipie/http/slice/SliceDownload.java
> +                                                    content
@g4s8 Done.

2021-02-09 09:25 UTC, andreoss commented on src/main/java/com/artipie/http/slice/SliceDownload.java
> +                                            )
@g4s8 Done.

2021-02-09 09:38 UTC, g4s8 approved these changes
@andreoss thanks

2021-02-09 09:39 UTC, merged

2021-02-09 10:23 UTC, 0crat commented
Job `gh:artipie/http#287` is not assigned, can't get performer

<!-- https://www.0crat.com/footprint/CT2E6TK9B/5bb9b6fd-4a4f-435f-913b-91d3eadc200e, version: 0.55, hash: ${buildNumber} -->