Added class to parse `Accept` header
artipie/http pull request #298
Opened 2021-04-23 13:01 UTC by olenagerasimova

Closes #297 
Added class to parse `Accept` header and corresponding test.

2021-04-23 13:29 UTC, genryxy requested changes
@olenagerasimova thanks, two comments

2021-04-23 13:29 UTC, genryxy commented on src/main/java/com/artipie/http/headers/Accept.java
> +    public Accept(final Iterable<Map.Entry<String, String>> headers) {
@olenagerasimova probably pass `Headers` instead of `Iterable<Map.Entry<String, String>>` as it `Headers` extends the last one

2021-04-23 13:29 UTC, genryxy commented on src/test/java/com/artipie/http/headers/AcceptTest.java
> +                    new Header("Accept", "text/html, application/xml;q=0.9, audio/aac;q=0.4"),
@olenagerasimova is it possible that the first header and the second will contain the same value, for example `text/html`

2021-04-26 06:59 UTC, olenagerasimova commented on src/main/java/com/artipie/http/headers/Accept.java
> +    public Accept(final Iterable<Map.Entry<String, String>> headers) {
@genryxy hm, I'd prefer to leave `Iterable` as it's more general and we can pass `Headers`

2021-04-26 06:59 UTC, olenagerasimova commented
@genryxy thanks, fixed and answered

2021-04-26 07:05 UTC, genryxy submitted a review, later dismissed
@olenagerasimova thanks, looks good to me

2021-04-26 07:27 UTC, g4s8 requested changes
@olenagerasimova just a minor comment

2021-04-26 07:27 UTC, g4s8 commented on src/main/java/com/artipie/http/headers/Accept.java
> +            .sorted((one, two) -> Float.compare(one.getValue(), two.getValue()) * (-1))
@olenagerasimova you could just switch arguments of `Float.compare` instead of `* (-1)`:
```java
.sorted((one, two) -> Float.compare(two.getValue(),  one.getValue()))
```

2021-04-26 08:36 UTC, olenagerasimova commented
@g4s8 thanks, done

2021-04-26 09:25 UTC, g4s8 approved these changes
@olenagerasimova thanks

2021-04-26 09:25 UTC, merged