Added multipart headers builder
artipie/http pull request #318
Opened 2021-05-24 13:46 UTC by g4s8

For #229 - added classes to build multipart request headers from ByteBuffer chunks.

2021-05-24 14:19 UTC, olenagerasimova requested changes
@g4s8 thanks, hm, what if we use `Optional` for `data` and `cache` to avoid `nulls`? And there is another comment

2021-05-24 14:19 UTC, olenagerasimova commented on src/main/java/com/artipie/http/rq/multipart/MultipartHeaders.java
> +        synchronized (this.lock) {
@g4s8 seems like another check `this.data == null` is required after the lock was obtained

2021-05-25 06:10 UTC, g4s8 commented
@olenagerasimova thanks, the `null` is used here only to notify the GC that the buffer and it's back-end byte-array can be removed from heap. I moved the common logic of working with byte-buffers into a new class, please see new commit: https://github.com/artipie/http/pull/318/commits/33c0d78ddca896648cf0ad9fddd1f36d982222b3

2021-05-25 06:41 UTC, olenagerasimova approved these changes
@g4s8 thanks, looks good to me

2021-05-25 06:41 UTC, merged