feat: Creates HeadSlice
artipie/http pull request #399
Opened 2021-10-29 17:09 UTC by baudoliver7

Closes #397 

- Creates `HeadSlice`
- Introduces tests
- Introduces puzzle to use `HeadSlice` instead of `BlobMetadataSlice` in `artipie/files-adapter` (after releasing `artipie/http` project)

2021-11-01 11:54 UTC, olenagerasimova approved these changes
@baudoliver7 thanks, looks good

2021-11-01 12:13 UTC, g4s8 requested changes
@baudoliver7 please check my comments

2021-11-01 12:13 UTC, g4s8 commented on src/test/java/com/artipie/http/slice/BlobMetadataSliceTest.java
> +     *   fixing this issue, remove {@code new ContentLength(0)} in the test below.
It's not a valid issue if you use `RsWithHeaders`

2021-11-01 12:13 UTC, g4s8 commented on src/main/java/com/artipie/http/slice/BlobMetadataSlice.java
> +public final class BlobMetadataSlice implements Slice {
I think the name here should be more generic than for files-adapter, e.g. it could be `HeadSlice` or similar

2021-11-01 12:13 UTC, g4s8 commented on src/main/java/com/artipie/http/slice/BlobMetadataSlice.java
> +                                                        ),
This part should be moved to a separate function field, since we may have another headers to return in different adapters, e.g. maven adapter reads checksum files to add it to headers. The default behavior is OK now, so you can just move this implementation to default parameter in secondary constructor. See https://github.com/artipie/http/issues/397:
> make it more flexible to add additional data to response headers which may be needed for concrete adapters implementation

2021-11-01 12:13 UTC, g4s8 commented on src/main/java/com/artipie/http/slice/BlobMetadataSlice.java
> +                                                    new RsFull(
You can use [RsWithHeaders](https://github.com/artipie/http/blob/master/src/main/java/com/artipie/http/rs/RsWithHeaders.java#L47) class to wrap `OK` response without using `RsFull` since we don't need body here:
```java
new RsWithHeaders(
  new Headers.From(...),
  StandardRs.OK
)
```
Then you won't get content-length duplication

2021-11-01 12:13 UTC, g4s8 commented on src/main/java/com/artipie/http/slice/BlobMetadataSlice.java
> + * @todo #397:30min Use this class in artipie/files-adapter.
And this puzzle is also not valid then

2021-11-01 12:35 UTC, baudoliver7 commented on src/main/java/com/artipie/http/slice/BlobMetadataSlice.java
> +public final class BlobMetadataSlice implements Slice {
@g4s8 let's use `HeadSlice`. It's more convenient :)

2021-11-01 12:48 UTC, baudoliver7 commented on src/main/java/com/artipie/http/slice/BlobMetadataSlice.java
> +                                                        ),
@g4s8 regardless of adapter, we always have uri and length content. So wouldn't it be better to simply pass via constructor only additional headers if they exists ?

2021-11-01 13:39 UTC, baudoliver7 commented on src/main/java/com/artipie/http/slice/BlobMetadataSlice.java
> + * @todo #397:30min Use this class in artipie/files-adapter.
@g4s8 we need also release of artipie/http (that can take one day) as prerequisites before using it in `artipie/files-adapter` :)

2021-11-01 13:55 UTC, baudoliver7 commented on src/main/java/com/artipie/http/slice/BlobMetadataSlice.java
> +                                                        ),
@g4s8 you will see in the latest commit my suggestion.

2021-11-02 08:12 UTC, baudoliver7 commented
@g4s8 please, could you review my latest changes and my comments ?

2021-11-03 07:44 UTC, g4s8 requested changes
@baudoliver7 please check my comments

2021-11-03 07:44 UTC, g4s8 commented on src/main/java/com/artipie/http/slice/HeadSlice.java
> +    private final Function<Storage, CompletionStage<Headers>> addhdrs;
This is not correct:
 1. `Storage` is already encapsulated - no need to pass it as a parameter
 2. It's not possible to read request data in this function, which is required to determine head response

I think we can go with one of these options: either change it to `BiFunction<String, Headers, CompletionStage<Headers>>` to take request line and request headers as parameters and return async response headers; or create custom `@FunctionalInterface` for this type: `(String, Headers) -> CompletionStage<Headers>`

2021-11-03 07:44 UTC, g4s8 commented on src/main/java/com/artipie/http/slice/HeadSlice.java
> +     * @param addhdrs Additional headers
It's not actually additional headers but the function to make response headers from request parameters

2021-11-03 07:44 UTC, g4s8 commented on src/main/java/com/artipie/http/slice/HeadSlice.java
> +    public HeadSlice(
We need a secondary constructor with default implementation of headers func as in current `response` method

2021-11-03 07:44 UTC, g4s8 commented on src/main/java/com/artipie/http/slice/HeadSlice.java
> +                                            );
This should be the result of response headers func:
```java
this.resheaders.apply(line, headers).thenApply(headers -> new RsWithHeaders(StandardRs.OK, headers))
```
```

2021-11-03 07:55 UTC, baudoliver7 commented on src/main/java/com/artipie/http/slice/HeadSlice.java
> +    private final Function<Storage, CompletionStage<Headers>> addhdrs;
@g4s8 The first suggestion is ok for me :)

2021-11-03 08:28 UTC, baudoliver7 commented on src/main/java/com/artipie/http/slice/HeadSlice.java
> +     * @param addhdrs Additional headers
@g4s8 agree with you

2021-11-03 08:29 UTC, baudoliver7 commented on src/main/java/com/artipie/http/slice/HeadSlice.java
> +                                            );
@g4s8 ok

2021-11-03 08:51 UTC, g4s8 approved these changes
@baudoliver7 thanks!

2021-11-03 08:55 UTC, merged