Added `GzipSlice`
artipie/http pull request #405
Opened 2021-11-22 13:58 UTC by olenagerasimova

Part of #404 
Added `GzipSlice` and test.

2021-11-22 15:06 UTC, genryxy requested changes
@olenagerasimova thanks, one question

2021-11-22 15:06 UTC, genryxy commented on src/main/java/com/artipie/http/slice/GzipSlice.java
> +        ) {
is it possible that this streams will be closed before the target operation is finished? Because the result of this operation is `CompletionStage` and it seems that these streams could be closed earlier that it should be

2021-11-22 15:46 UTC, genryxy commented on src/main/java/com/artipie/http/slice/GzipSlice.java
> +        ) {
but `tmpout` and `resout` are used in one of the stage of `CompletableFuture`. Probably I am wrong and it does not matter in this case

2021-11-22 18:15 UTC, olenagerasimova commented on src/main/java/com/artipie/http/slice/GzipSlice.java
> +        ) {
These are piped input/output streams, and they are being processed when we gzip the content. After gzip workflow is fully done (input/output streams read/written fully), there is nothing to do in corresponding piped stream, that are used in the futures, so these streams can be closed.

2021-11-22 19:24 UTC, genryxy commented on src/main/java/com/artipie/http/slice/GzipSlice.java
> +        ) {
Okay, although I don't fully understand why after finishing gzip all workflow is fully done. In this case reading in `GZIPOutputStream` looks like a blocking operation therefore it should be wrapped in future

2021-11-23 05:30 UTC, olenagerasimova commented on src/main/java/com/artipie/http/slice/GzipSlice.java
> +        ) {
Can you just pass this PR to next review stage, please? The arc will decide is there smth wrong or not

2021-11-23 05:34 UTC, genryxy reviewed
@g4s8 could you please take a look

2021-11-24 07:40 UTC, olenagerasimova commented
@g4s8 ping

2021-11-24 09:08 UTC, g4s8 requested changes
@olenagerasimova gzip slice should encapsulate another sluce, not storage. It compress the response body of some origin slice which may produce dynamic content. Also, it keeps origin headers and adds content-encoding header to it.

2021-11-24 10:07 UTC, olenagerasimova commented
@g4s8 done, please, take a look

2021-11-24 14:40 UTC, kirill-h5i requested changes
@olenagerasimova just one minor comment about javadoc

2021-11-24 14:40 UTC, kirill-h5i commented on src/main/java/com/artipie/http/slice/GzipSlice.java
> +     * Gzip storage item.
> storage item

The javadoc is wrong here

2021-11-24 14:50 UTC, olenagerasimova commented
@kirill-h5i thanks, corrected java doc

2021-11-25 06:31 UTC, olenagerasimova commented
@g4s8 please, take a look/merge

2021-11-25 08:18 UTC, g4s8 approved these changes
@olenagerasimova thanks

2021-11-25 08:38 UTC, olenagerasimova commented
@genryxy please, approve

2021-11-25 08:39 UTC, genryxy approved these changes
@olenagerasimova thanks, sorry for wrong suggestions

2021-11-25 08:39 UTC, merged