Added `WithGzipSlice`
artipie/http pull request #408
Opened 2021-11-25 09:20 UTC by olenagerasimova

Closes #404 
Added `WithGzipSlice` to process request with respect to `accept-encoding` header.

2021-11-25 11:12 UTC, genryxy requested changes
@olenagerasimova thanks, minor comment about version

2021-11-25 11:12 UTC, genryxy commented on src/test/java/com/artipie/http/slice/WithGzipSliceTest.java
> + * @since 1.2
`@since` is wrong

2021-11-25 11:12 UTC, genryxy commented on src/main/java/com/artipie/http/slice/WithGzipSlice.java
> + */
and here

2021-11-25 11:15 UTC, olenagerasimova commented
@genryxy thanks, fixed tags

2021-11-25 11:15 UTC, genryxy submitted a review, later dismissed
@olenagerasimova thanks, looks good

2021-11-25 11:19 UTC, olenagerasimova commented
@g4s8 please, take a look/merge

2021-11-25 12:22 UTC, g4s8 requested changes
@olenagerasimova thanks, just minor suggestion

2021-11-25 12:22 UTC, g4s8 commented on src/main/java/com/artipie/http/slice/WithGzipSlice.java
> + * compress output body with gzip and adds `Content-Encoding: gzip` header.
```suggestion
 * compress output body with gzip and adds {@code Content-Encoding: gzip} header.
```

2021-11-25 13:53 UTC, olenagerasimova commented
@g4s8 thanks, applied your suggestion

2021-11-26 12:05 UTC, olenagerasimova commented
@g4s8 please, take a look/merge

2021-11-26 12:10 UTC, g4s8 approved these changes
@olenagerasimova thanks

2021-11-26 12:10 UTC, merged