feat: return a list of the files present in a directory
artipie/http pull request #415
Opened 2021-12-25 08:49 UTC by dgarus

Closes #158

- added `SliceListing`
- added `todo` to test `SliceListing`
- added `todo` to implement `HTML` format

2021-12-25 09:13 UTC, dgarus commented
@g4s8 could you please have a look?

2021-12-27 06:32 UTC, g4s8 requested changes
@dgarus thanks, please check my comments

2021-12-27 06:32 UTC, g4s8 commented on src/main/java/com/artipie/http/slice/SliceListing.java
> +    private final Function<Collection<? extends Key>, String> format;
Does it work for `Function<List<Key>, String>`? Maybe we should change it to `Function<? extends Collection<? extends Key>>, String>`?

2021-12-27 06:32 UTC, g4s8 commented on src/main/java/com/artipie/http/slice/SliceListing.java
> +        final SliceListing.Standard standard
I don't think it's a good idea to have such a string coupling for enum type here, since it's not really extensible.

2021-12-27 06:32 UTC, g4s8 commented on src/main/java/com/artipie/http/slice/SliceListing.java
> +                                                StandardCharsets.UTF_8
Encoding should be determined with HTTP [content-negotiation](https://developer.mozilla.org/en-US/docs/Web/HTTP/Content_negotiation):
 - parse encoding from `accept` header if present or use default
 - add encoding to `Content-type` response header
 - encode HTTP body with this encoding

2021-12-27 06:32 UTC, g4s8 commented on src/main/java/com/artipie/http/slice/SliceListing.java
> +    enum Standard implements Function<Collection<? extends Key>, String> {
It's not a correct place for this enum (`SliceListing.Standard` - means standard implementations of slice listing slice?). We either need a type interface for format and put enum as nested type here as `ListingFormat.Standard` or create separate type `StandardListingFormats`

2021-12-27 06:32 UTC, g4s8 commented on src/main/java/com/artipie/http/slice/SliceListing.java
> +        private final String mtype;
I don't agree that mime keeping a mime type is a responsibility of listing output format:
 1. We may want to return the same format with different types (e.g. `application/json` if `Accept` header is `application/json` or `application/octet-stream` if `Accept` header is `application/octet-stream`)
 2. It's related to to HTTP layer (slice) to negotiate the correct `Content-type` response header, so it may want to use some additional mime-type parameters (like `charset` or others: `Content-type: application/json; charset=utf-8`)

2021-12-28 14:11 UTC, dgarus commented on src/main/java/com/artipie/http/slice/SliceListing.java
> +                                                StandardCharsets.UTF_8
@g4s8 
Do we really need to support the `Accept-Charset` header?
The [documentation](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Charset) contains the warning: Do not use this header. Browsers omit this header and servers should ignore it.

2021-12-28 14:34 UTC, dgarus commented on src/main/java/com/artipie/http/slice/SliceListing.java
> +    enum Standard implements Function<Collection<? extends Key>, String> {
I did a separate type ListingFormat with enum.

2022-01-10 07:52 UTC, g4s8 commented on src/main/java/com/artipie/http/slice/SliceListing.java
> +                                                StandardCharsets.UTF_8
No, the charset can be included into the mime type which is present by `Content-Type` header, e.g. `Content-type: application/json;encoding=utf-8`

2022-01-12 16:14 UTC, dgarus commented on src/main/java/com/artipie/http/slice/SliceListing.java
> +                                                StandardCharsets.UTF_8
Thanks, I got it.
Added todo to implement Accept-Encoding header.

2022-01-12 16:16 UTC, dgarus commented
@g4s8 hello!
Could you please have a look?

2022-01-21 09:08 UTC, g4s8 requested changes
Thanks, please check my comment. Also, there are a lot of warnings in this PR about test coverage, please transfer related test from files-adapter: https://github.com/artipie/files-adapter/blob/master/src/test/java/com/artipie/files/BlobListFormatTest.java

2022-01-21 09:08 UTC, g4s8 commented on src/main/java/com/artipie/http/slice/SliceListing.java
> +                                                StandardCharsets.UTF_8
The origin comment here was only about mime-type encoding only, not about other accept values included in header: current problem that this code hard-codes UTF-8 charset encoding for response, but client may request another encoding for this particular media type, e.g. `Accept: application/json;encoding=ISO-885901` (some windows encoding) - and it will be an error if we respond with `Content-Type: application/json;encoding=UTF-8` and this may cause runtime errors on client side. Of course we can use `UTF-8` as a default encoding here (if client doesn't specify it in accept header).

2022-01-21 11:40 UTC, dgarus commented on src/main/java/com/artipie/http/slice/SliceListing.java
> +                                                StandardCharsets.UTF_8
@g4s8 Oh, I understood the problem is misusing words 'charset' and 'encoding'.

UTF-8 is charset, so the expected charset could be pointed by the [Accept-Charset](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Charset) header. 
The header [Accept](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept) does not contain a 'charset' part:
`Accept: <MIME_type>/<MIME_subtype>`

Response's `Content-Type` header may contain a 'charset' part.
We should support the `Accept-Charset` header to enable a custom charset. 

But the documentation contains the warning: 
`Do not use Accept-Charset header. Browsers omit this header, and servers should ignore it. `

That is why I asked Do we need to support the `Accept-Charset` header? 

If this is the case, I'll create a to-do: "Add support for the `Accept-Charset` header."

2022-01-21 12:08 UTC, dgarus commented on src/main/java/com/artipie/http/slice/GzipSliceListing.java
> +public class GzipSliceListing extends Slice.Wrap {
I deleted GzipSliceListing.

2022-01-21 13:58 UTC, g4s8 commented on src/main/java/com/artipie/http/slice/SliceListing.java
> +                                                StandardCharsets.UTF_8
@dgarus I see now, thanks, if `Accept` can't contain charset MIME-param and `accept-charset` is obsolete, then we don't really need to negotiate client's encoding. Sorry for misunderstanding.

2022-01-21 14:00 UTC, g4s8 approved these changes
@dgarus thanks

2022-01-21 14:22 UTC, merged