test: add test for SliceListing
artipie/http pull request #451
Opened 2022-06-06 11:31 UTC by Swizbiz

Add unit tests for text and json mime types

Close: #426

2022-06-06 11:55 UTC, Swizbiz commented
@olenagerasimova please check PR

2022-06-06 12:30 UTC, olenagerasimova requested changes
@Swizbiz thanks, added several minor comments, please, take a look

2022-06-06 12:30 UTC, olenagerasimova commented on src/test/java/com/artipie/http/slice/SliceListingTest.java
> +        "one/, 'one/target1.txt\none/two/target2.txt'"
How junit treats the space in such `CsvSource` format? Skips it as part of the separator or treats it as part of the value? As far as know, default separator is comma `,` and `''` (double single quotes) produces empty string and are required only to obtain this empty string value. So, to avoid any misunderstanding and confusion, I'd suggest to remove the spaces in separator and use single quotes only when required

2022-06-06 12:30 UTC, olenagerasimova commented on src/test/java/com/artipie/http/slice/SliceListingTest.java
> + * @since 1.1.4
Usually we place only two digits into since value tag adding one to the second digit, so if current version is 1.1.3, then since will be 1.2. There is no need to fix it, it's just so you know for the future

2022-06-06 12:30 UTC, olenagerasimova commented on src/test/java/com/artipie/http/slice/SliceListingTest.java
> +    private static String get(final String path) {
I'd suggest to choose more verbose name for this method, for example `requestLine` or `rqLineFrom`, Yegor has a [blog post](https://www.yegor256.com/2014/04/27/typical-mistakes-in-java-code.html#method-names) about it, we try to follow his suggestions

2022-06-06 12:30 UTC, olenagerasimova commented on src/test/java/com/artipie/http/slice/SliceListingTest.java
> +        final Storage storage = new InMemoryStorage();
I'd suggest to extract `Storage` into private field and initialize it in `@BeforeEach` method, thus we avoid repeating initialization in each test

2022-06-06 12:55 UTC, Swizbiz commented on src/test/java/com/artipie/http/slice/SliceListingTest.java
> +        "one/, 'one/target1.txt\none/two/target2.txt'"
Junit skip space, but I remove it for common style.

2022-06-06 13:27 UTC, Swizbiz commented
> @Swizbiz thanks, added several minor comments, please, take a look

@olenagerasimova done

2022-06-06 13:44 UTC, olenagerasimova requested changes
@Swizbiz thanks, one more suggestion, please, take a look

2022-06-06 13:44 UTC, olenagerasimova commented on src/test/java/com/artipie/http/slice/SliceListingTest.java
> +    private final Storage storage = new InMemoryStorage();
It would be better to do the initialization in `BeforeEach` method, thus each test method will work with new clean empty storage and we will never have some sort of data collision

2022-06-07 06:49 UTC, Swizbiz commented
> @Swizbiz thanks, one more suggestion, please, take a look

@olenagerasimova done

2022-06-07 06:55 UTC, olenagerasimova approved these changes
@Swizbiz thanks

2022-06-07 06:55 UTC, merged