feat: add HTML standard format for ListingFormat
artipie/http pull request #456
Opened 2022-06-14 11:38 UTC by Swizbiz

implement HTML format for slice listing and tests for this

close: #430

2022-06-14 13:54 UTC, olenagerasimova commented
@dgarus please, take a look

2022-06-14 14:29 UTC, dgarus requested changes
@Swizbiz thanks!
Pay attention to my comments, please.

2022-06-14 14:29 UTC, dgarus commented on src/main/java/com/artipie/http/slice/ListingFormat.java
> +                        key.string(),
Method `string()` can take some resources.
Could we create a variable here and use it twice?

2022-06-14 14:29 UTC, dgarus commented on src/test/java/com/artipie/http/slice/ListingFormatTest.java
> +    void formatHtmlKeys() throws IOException {
Unused `IOException`

2022-06-14 14:53 UTC, Swizbiz commented on src/main/java/com/artipie/http/slice/ListingFormat.java
> +         * Json format renders keys as JSON array with
fixed

2022-06-14 14:53 UTC, Swizbiz commented on src/main/java/com/artipie/http/slice/ListingFormat.java
> +                        key.string(),
done

2022-06-14 14:54 UTC, Swizbiz commented on src/test/java/com/artipie/http/slice/ListingFormatTest.java
> +    void formatHtmlKeys() throws IOException {
removed

2022-06-14 14:54 UTC, Swizbiz commented
@dgarus please check again

2022-06-15 06:53 UTC, Swizbiz commented
@olenagerasimova ready to merge, please check

2022-06-20 06:08 UTC, olenagerasimova approved these changes
@Swizbiz thanks

2022-06-20 06:08 UTC, merged