Readme
artipie/http pull request #457
Opened 2022-06-20 14:19 UTC by Swizbiz

clean up readme

2022-06-20 14:19 UTC, Swizbiz commented
@artipie/members please check PR

2022-06-20 14:44 UTC, dgarus requested changes
@Swizbiz, there are minor comments, please, have a look.

2022-06-20 14:44 UTC, dgarus commented on README.md
> +If you have any question or suggestions, do not hesitate to create as issue or contact us in
typo: `as issue` -> `an issue`

2022-06-20 14:44 UTC, dgarus commented on README.md
> +[Telegram](https://t.me/artipie), our roadmap is available [here](https://github.com/orgs/artipie/projects/3).
Maybe `our roadmap is` should be a separate sentence?

2022-06-20 14:51 UTC, Swizbiz commented
@dgarus done, please check again

2022-06-20 14:53 UTC, dgarus approved these changes

2022-06-20 14:54 UTC, dgarus commented
@Swizbiz thanks!
LGTM

@olenagerasimova, could you please check and merge?

2022-06-21 09:03 UTC, dgarus requested changes
minor comment

2022-06-21 09:03 UTC, dgarus commented on README.md
> +Artipie HTTP base interfaces
Dot is absent.

2022-06-21 09:22 UTC, merged