feat: yaml policy and user permissions
artipie/http pull request #505
Opened 2023-01-20 11:17 UTC by olenagerasimova

part of #501 

Implemented `YamlPolicy` and corresponding tests, added `UserPermissions` (tests will added in the next step), moved test classes.

2023-01-20 14:00 UTC, dgarus requested changes
@olenagerasimova thanks!
Please check my comments.

2023-01-23 06:30 UTC, olenagerasimova commented on src/main/java/com/artipie/security/policy/YamlPolicy.java
> +        return new UserPermissions(urs.perms(), urs.roles(), new Roles(this.asto));
Let's discuss it at the office.

2023-02-06 10:13 UTC, olenagerasimova commented
@dgarus please, take a look. The PR was updated

2023-02-07 11:41 UTC, dgarus requested changes
@olenagerasimova thanks!
Please have a look at my comments.

2023-02-07 11:41 UTC, dgarus commented on src/main/java/com/artipie/security/perms/AdapterBasicPermission.java
> +        } else if (actions.contains(Action.ALL.names().iterator().next())) {
Overcomplicated

```
if (actions.contains("*"))
```

2023-02-07 13:58 UTC, olenagerasimova commented on src/main/java/com/artipie/security/test/FreePermissions.java
> +public final class FreePermissions extends PermissionCollection {
Please, check the implementation from jdk. Java's `AllPermissionCollection` does not imply any permission BEFORE `add()` method was called. In our use cases `add()` method will not be called at all.

2023-02-07 14:04 UTC, olenagerasimova commented on src/main/java/com/artipie/security/policy/Policy.java
> +    Policy<PermissionCollection> FREE = uname -> new FreePermissions();
hm, actually, I've used it in [the main code](https://github.com/artipie/artipie/pull/1238/files#diff-75ba0295cba8b6bade3b7b3e076c2bb660e615d75ac94631157413483a3a6541) to support the situation when artipie is working without any security policy at all. Support for such case is required as we can work in such mode now.

So, maybe I should remove this `test` package?

2023-02-07 14:08 UTC, olenagerasimova commented on src/main/java/com/artipie/security/test/PolicyByUsername.java
> +public final class PolicyByUsername implements Policy<PermissionCollection> {
We use such approach (allow all actions for specific user) in the tests in each adapter, the example is [here](https://github.com/artipie/files-adapter/pull/146/files#diff-b7967f22526a85faa437c09722fad023482ced1942a813642690d5ca76dd5225). So, there are two options: it will be copied into each adapter or we can create it one time here.

2023-02-08 06:49 UTC, olenagerasimova commented on src/main/java/com/artipie/http/auth/AuthzSlice.java
> +        if (this.control.allowed(Authentication.ANY_USER)) {
this condition will work in the case when artipie is working in "no policy" mode, in this case we do not require authentication. This mode is used in all ITs in artipie and can be used by our users to try it out.

2023-02-08 06:50 UTC, olenagerasimova commented on src/main/java/com/artipie/http/auth/AuthzSlice.java
> +                    result -> result.user().map(this.control::allowed).map(
here we check if user have required permission, check `AccessControl` interface. Also, any suggestions to improve classes and interfaces names are welcome.

2023-02-08 07:05 UTC, olenagerasimova commented
@dgarus thanks, corrected and answered

2023-02-08 07:15 UTC, Swizbiz commented on src/main/java/com/artipie/security/policy/YamlPolicy.java
> + * <pre>{@code
David has an email listed as jane@example.com

2023-02-08 08:13 UTC, olenagerasimova commented
@dgarus @Swizbiz all fixed, thanks

2023-02-09 14:15 UTC, olenagerasimova commented
@dgarus please, review. I've added caching with guava cache. The invalidation will be required in the case when policy is updated via REST API. We can update the policy via rest api if and only if our own yaml policy `CachedYamlPolicy` is used (in other cases we just have no idea where, what and how to update), which means we need to check if the `Policy<C extends PermissionCollection>` is actually `CachedYamlPolicy`. So, it means we can perform class cast safely and call `invalidate()` method.

2023-02-13 10:54 UTC, dgarus requested changes
Thanks!
Please take a look at my comments.

2023-02-13 10:54 UTC, dgarus commented on src/main/java/com/artipie/security/policy/CachedYamlPolicy.java
> +                () -> this.users.get(uname, () -> new User(this.asto, uname).perms())
Think, we could create `new User(this.asto, uname)` only ones to get user permission and a set of roles.

2023-02-13 10:54 UTC, dgarus commented on src/main/java/com/artipie/security/perms/UserPermissions.java
> +        final String ref = this.last.get();
This method is not thread safe because of `this.last` state field

2023-02-13 10:54 UTC, dgarus commented on src/main/java/com/artipie/security/policy/CachedYamlPolicy.java
> +                            type, new PermissionConfig.Yaml(Yaml.createYamlMappingBuilder().build())
`new PermissionConfig.Yaml(Yaml.createYamlMappingBuilder().build())` can be a constant.

2023-02-13 11:44 UTC, olenagerasimova commented on src/main/java/com/artipie/security/perms/AdapterBasicPermission.java
> +                this.perms.put(permission.getName(), permission);
`isReadOnly()` check added, `getCanonicalName()` method exists in java's `BasicPermission` only, is final and has nothing to do with our `AdapterBasicPermission`. As for class name check - `AdapterBasicPermission` is final, no point to check.

2023-02-15 07:36 UTC, olenagerasimova commented
@dgarus as we discussed, I've reduced the amount of caches and joined user individual permissions and roles.

2023-02-15 11:45 UTC, olenagerasimova commented
@dgarus ping, please review

2023-02-15 12:20 UTC, Swizbiz reviewed
@olenagerasimova Thank you!
Please, check my comments.

2023-02-15 12:20 UTC, Swizbiz commented on src/test/java/com/artipie/security/perms/AdapterBasicPermissionTest.java
> +class AdapterBasicPermissionTest {
Since we can use not only the "read" action, but also "r", "download", "install", "pull". I think we should add some tests with them. 
And the same with the WRITE("write", "w", "publish", "push", "deploy", "upload") and DELETE("delete", "d", "remove") actions.

2023-02-15 12:20 UTC, Swizbiz commented on src/test/java/com/artipie/security/policy/CachedYamlPolicyTest.java
> +    void aliceCanReadFromMavenWithJavaDevRole() {
I think we can give Alice 2 roles and check the size of the relevant caches as 2.

2023-02-15 13:37 UTC, olenagerasimova commented on src/main/java/com/artipie/security/policy/CachedYamlPolicy.java
> +                if (Boolean.FALSE.toString().equalsIgnoreCase(enabled)) {
Unfortunately no as `enabled` is nullable and `null` means that optional field is missing and user is enabled. 
(When parsing booleans null means false)

2023-02-15 13:37 UTC, olenagerasimova commented on src/main/java/com/artipie/security/policy/CachedYamlPolicy.java
> +            return Boolean.FALSE.toString().equalsIgnoreCase(this.yaml.string(AstoRoles.ENABLED));
same here

2023-02-15 13:53 UTC, olenagerasimova commented on src/test/java/com/artipie/security/perms/AdapterBasicPermissionTest.java
> +class AdapterBasicPermissionTest {
I've added separate test for `Action.Standard`, this one looks like complicated enough already

2023-02-15 13:55 UTC, olenagerasimova commented on src/test/java/com/artipie/security/policy/CachedYamlPolicyTest.java
> +    void aliceCanReadFromMavenWithJavaDevRole() {
Added another user with two roles and negative assertion. The order of checking roles is not guarantied, so in the positive case we can never load all the roles.

2023-02-15 13:56 UTC, olenagerasimova commented
@Swizbiz thanks, corrected and answered

2023-02-16 08:23 UTC, dgarus requested changes
Thanks!
Please take a look at my comments.

2023-02-16 08:23 UTC, dgarus commented on src/main/java/com/artipie/security/policy/CachedYamlPolicy.java
> +            this.yaml = getYamlMapping(asto, username);
I think we should read `perms` and `roles` in the `ctor`. 
They have to be read only once. There is no sense to recreate `PermissionCollection` or  `Set<String>` for every method call.

2023-02-16 08:23 UTC, dgarus commented on src/main/java/com/artipie/security/policy/CachedYamlPolicy.java
> +            this.asto = asto;
I think we should read `perms` in the `ctor`.
They have to be read only once. There is no sense to recreate `PermissionCollection` for every method call.

2023-02-16 08:23 UTC, dgarus commented on src/main/java/com/artipie/security/policy/CachedYamlPolicy.java
> +                    uname, () -> new User.Simple(astoUser.roles(), astoUser.perms())
We have to add to the cache `new AstoUser(this.asto, uname)` like we do with `AstoRoles`

2023-02-16 08:59 UTC, olenagerasimova commented on src/main/java/com/artipie/security/policy/CachedYamlPolicy.java
> +            this.asto = asto;
they are read only once, when requested role is not present in the cache.

2023-02-16 09:00 UTC, olenagerasimova commented on src/main/java/com/artipie/security/policy/CachedYamlPolicy.java
> +                    uname, () -> new User.Simple(astoUser.roles(), astoUser.perms())
I've correct the code, user yaml will be read and parsed only once in the case when `this.users` cache does not have corresponding user

2023-02-16 09:01 UTC, olenagerasimova commented on src/main/java/com/artipie/security/policy/CachedYamlPolicy.java
> +            this.yaml = getYamlMapping(asto, username);
agree, the instance of this class should be created only in `this.users` cache callable parameter

2023-02-16 09:06 UTC, olenagerasimova commented
@dgarus answered and corrected

2023-02-16 11:08 UTC, olenagerasimova commented
@dgarus done as you asked and from my point of view it's just disgusting and all the point of "custom user policy implementation" is nearly lost as now `UserPermissions` depends on some `AstoUser` which requires specific yamls

2023-02-16 11:22 UTC, dgarus commented
> 

Yes, you are right, interface `User` as parameter for `UserPermissions ` is useful.

Can we return it?

Sorry

2023-02-16 13:09 UTC, olenagerasimova commented
@dgarus it seems ok and convenient to use already existing `Function` interface to provide role's `PermissionCollection` by its name

2023-02-16 13:16 UTC, dgarus commented
> @dgarus it seems ok and convenient to use already existing `Function` interface to provide role's `PermissionCollection` by its name

In that case, we really could replace `AstoRole` by a static method.

2023-02-16 13:53 UTC, olenagerasimova commented
@dgarus done

2023-02-16 14:03 UTC, Swizbiz approved these changes
Thank you.

2023-02-16 14:26 UTC, merged