fix: perm for any repo
artipie/http pull request #518
Opened 2023-03-02 10:53 UTC by olenagerasimova

part of #501 

Added fix and tests for the case with `adapter_basic_permission` for any repository.

2023-03-02 13:22 UTC, olenagerasimova commented
@dgarus please, check, that's not big but important fix

2023-03-02 15:08 UTC, dgarus requested changes
@olenagerasimova thanks!
Please check my comment.

Do we really need a username in the permissions file? 
It looks like an info duplication because we already have username as file name.

2023-03-02 15:08 UTC, dgarus commented on src/test/java/com/artipie/security/policy/CachedYamlPolicyTest.java
> +
all these methods can be replaced by one
```
private byte[] userConfig(String user, String repo){
        String template = String.join(
            "\n",
            "%s:",
            "  permissions:",
            "    adapter_basic_permission:",
            "      %s:",
            "        - download"
        );
        return String.format(template, user, repo).getBytes(StandardCharsets.UTF_8);
    }
    
```

2023-03-03 07:56 UTC, olenagerasimova commented
@dgarus thanks, corrected

2023-03-03 08:22 UTC, dgarus approved these changes
thanks!

2023-03-03 08:23 UTC, merged