Repository content filters support
artipie/http pull request #524
Opened 2023-03-29 08:28 UTC by andpopov

Part of: https://github.com/artipie/artipie/issues/1254

Filters support for repository:
- Filter's yaml configuration format
- Filters API
- Globbing filter
- Regexp filter
- FilterSlice

2023-03-29 14:46 UTC, olenagerasimova requested changes
@andpopov thanks, please, check my comments

2023-03-29 14:46 UTC, olenagerasimova commented on src/main/java/com/artipie/http/filter/FilterSlice.java
> +        final FilterFactoryLoader loader) {
hm, I'd suggest to make `FilterFactoryLoader` private static field. The factory is one and only, there is no need to pass it into ctor. Also such approach guarantee it will not be pointlessly created on each ctor call

2023-03-29 14:46 UTC, olenagerasimova commented on src/main/java/com/artipie/http/filter/GlobFilter.java
> +        );
hm... Is it really legal to use file system path matcher with URI?

2023-03-29 14:46 UTC, olenagerasimova commented on src/main/java/com/artipie/http/filter/GlobFilter.java
> +public final class GlobFilter implements Filter {
please, add some docs here with config format and examples. It will help with review and can be used in wiki later.

2023-03-29 14:46 UTC, olenagerasimova commented on src/main/java/com/artipie/http/filter/RegexpFilter.java
> +public final class RegexpFilter implements Filter {
same request about java doc

2023-03-29 14:46 UTC, olenagerasimova commented on src/test/java/com/artipie/http/filter/FiltersTest.java
> +                "    filter: **/com/artipie/**",
hm what if we change format this way:
```yaml
include:
  glob:
    - **/com/acme/**
    - **/com/artipie/**"
   regexp:
    - regexp1
    - regexp2
exclude:
  ...
```

It will shorter (as there will be no need to repeat "type: glob") and canonical with permission settiongs.

2023-03-29 14:46 UTC, olenagerasimova commented on src/test/java/com/artipie/http/filter/GlobFilterTest.java
> +    private static final String PATH = "/mvnrepo/com/artipie/inner/0.1/inner-0.1.pom";
what about line with request parameters?

2023-03-29 14:46 UTC, olenagerasimova commented on src/test/java/com/artipie/http/filter/RegexpFilterTest.java
> +    private static final String PATH = "/mvnrepo/com/artipie/inner/0.1/inner-0.1.pom";
same here, rq line can have parameters and other parts. I'd suggest to add corresponding tests...

2023-03-31 11:17 UTC, dgarus commented on src/test/java/com/artipie/http/filter/FiltersTest.java
> +                "    filter: **/com/artipie/**",
Maybe something like this?

```
include:
  - glob: **/com/acme/**
  - regexp: regexp1
  - glob: **/com/artipie/**"
  - regexp: regexp2
```

2023-03-31 11:32 UTC, andpopov reviewed
@olenagerasimova Please review changes

2023-03-31 11:32 UTC, andpopov commented on src/main/java/com/artipie/http/filter/FilterSlice.java
> +        final FilterFactoryLoader loader) {
add static instance to FilterSlice

2023-03-31 11:32 UTC, andpopov commented on src/main/java/com/artipie/http/filter/GlobFilter.java
> +public final class GlobFilter implements Filter {
added documentation.
GlobFilter matches only path part of request.

2023-03-31 11:32 UTC, andpopov commented on src/test/java/com/artipie/http/filter/GlobFilterTest.java
> +    private static final String PATH = "/mvnrepo/com/artipie/inner/0.1/inner-0.1.pom";
only path part of requestis used for matching

2023-03-31 11:51 UTC, andpopov commented on src/test/java/com/artipie/http/filter/FiltersTest.java
> +                "    filter: **/com/artipie/**",
The FactoryLoader need some explicit property to detect type of filter, this is reason why 'type: glob' is explicit syntax.
For example RegExp filter support several properties:
Yaml format:
  type: regexp
  filter: regular_expression
  raw: true
  case_insensitive: true

  where
    'type' is mandatory with value 'regexp'.
    'filter' is mandatory and value contains regular expression for request matching.
    'full_uri' is optional with default with value 'false'
      and implies to match with full uri or path part of uri.
    'case_insensitive' is optional with default value 'false'
      and implies to ignore case in regular expression matching.

Filter can have own set of properties and it is unclear how to detect type without explicit named property.

2023-04-03 07:39 UTC, olenagerasimova commented
@andpopov thanks, note, please, that CI is failing. Generally, it's better to make sure all the checks passed before asking for  review. As for format, discuss it with Denis, please.

2023-04-03 13:27 UTC, andpopov commented
@olenagerasimova, @dgarus
Changed format and added priotiry property for filter in yaml format.
Please review

2023-04-03 14:04 UTC, dgarus approved these changes
Thanks!

2023-04-03 14:43 UTC, olenagerasimova approved these changes
@andpopov thanks

2023-04-03 15:29 UTC, merged