feat: added base job
artipie/http pull request #551
Opened 2023-07-06 09:33 UTC by olenagerasimova

part of https://github.com/artipie/artipie/issues/1291

Added base job, which extends quartz job and have useful method to shut down the job. This class can be extended in the adapters to create jobs to process proxy repositories. 

Added method to start provided job class with provided job data map.

Added class for proxy events with artifact key, repo name and owner login.

2023-07-19 13:39 UTC, dgarus requested changes
Thanks!
Please look at my comment.

2023-07-19 13:39 UTC, dgarus commented on src/main/java/com/artipie/scheduling/EventQueue.java
> +public interface EventQueue<T> {
Why do we need this interface? Can we use pure `Queue<T>`?

2023-07-25 07:34 UTC, olenagerasimova commented on src/main/java/com/artipie/scheduling/EventQueue.java
> +public interface EventQueue<T> {
we can, but with our own interface we can hide under it's hood anything we want, even not a queue, also we can extend it how we want and need. 
Also, if switch to queue now, we will need to correct a lot of adapter again.

2023-07-25 08:15 UTC, olenagerasimova commented
@dgarus thanks, removed queue interface. As for test queue implementation: we can simply use java `LinkedQueue`, no other implementations required

2023-07-25 08:20 UTC, dgarus approved these changes
Thanks!
lgtm

2023-07-25 08:21 UTC, merged